// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
)

type Author struct {
	ID        int32
	FirstName string
	LastName  string
	CreatedAt sql.NullTime
}

type Book struct {
	ID        int32
	Title     string
	Author    string
	CreatedAt sql.NullTime
	AuthorID  sql.NullInt32
}

type SchemaMigration struct {
	Version string
}
